---
- name: Generate Private Key - fluentd.key
  community.crypto.openssl_privatekey:
    path: "{{ orc8r_secrets_directory }}/fluentd.key"
    size: 2048

- name: Generate Certificate Signing Request - fluentd.csr
  community.crypto.openssl_csr:
    path: "{{ orc8r_secrets_directory }}/fluentd.csr"
    privatekey_path: "{{ orc8r_secrets_directory }}/fluentd.key"
    country_name: US
    common_name: fluentd.{{ orc8r_domain }}

- name: Generate Certificate - fluentd.pem
  community.crypto.x509_certificate:
    path: "{{ orc8r_secrets_directory }}/fluentd.pem"
    csr_path: "{{ orc8r_secrets_directory }}/fluentd.csr"
    ownca_path: "{{ orc8r_secrets_directory }}/certifier.pem"
    ownca_privatekey_path: "{{ orc8r_secrets_directory }}/certifier.key"
    provider: ownca

- name: Delete - fluentd.csr
  file:
    path: "{{ orc8r_secrets_directory }}/fluentd.csr"
    state: absent
