---
- name: Set Orc8r Docker images
  set_fact:
    orc8r_docker_images:
      - docker.elastic.co/elasticsearch/elasticsearch:7.17.1
      - docker.io/bitnami/postgresql:14.2.0-debian-10-r25
      - docker.io/facebookincubator/alertmanager-configurer:1.0.4
      - docker.io/facebookincubator/prometheus-configurer:1.0.4
      - docker.io/facebookincubator/prometheus-edge-hub:1.1.0
      - docker.io/grafana/grafana:6.7.6
      - docker.io/haproxytech/haproxy-alpine:2.5.2
      - docker.io/library/alpine:latest
      - docker.io/library/busybox:latest
      - docker.io/library/nginx:latest
      - docker.io/magmacore/controller:1.6.1
      - docker.io/magmacore/magmalte:1.6.1
      - docker.io/magmacore/nginx:1.6.1
      - docker.io/prom/alertmanager:v0.18.0
      - docker.io/prom/prometheus:v2.27.1
      - gcr.io/google-containers/fluentd-elasticsearch:v2.4.0
      - quay.io/metallb/controller:v0.12.1
      - quay.io/metallb/speaker:v0.12.1

- name: Download Orc8r docker images
  become: yes
  with_items: "{{ orc8r_docker_images }}"
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull

- name: Load Docker images into Kind Cluster
  with_items: "{{ orc8r_docker_images }}"
  command: kind load docker-image {{ item }} --name {{ cluster_name }}
