---
- import_tasks: set-namespace.yml
- import_tasks: volume-claims.yml
- import_tasks: register-secrets.yml
- import_tasks: orc8r.yml
- import_tasks: lte-orc8r.yml
- import_tasks: feg-orc8r.yml
- import_tasks: cwf-orc8r.yml
- import_tasks: wifi-orc8r.yml
  when: deploy_wifi_orc8r
- import_tasks: domain-proxy.yml
  when: deploy_domain_proxy
- import_tasks: fbinternal-orc8r.yml
  when: deploy_fbinternal_orc8r
