---
- name: Check if Kind Cluster is running
  command: kind get clusters
  register: kind_cluster_running

- name: Create Kind Cluster
  when: not "orc8r" in kind_cluster_running.stdout
  shell: |
    kind create cluster --name {{ cluster_name }} --config - << EOF
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    EOF
